# Site settings
author: Thomas Harmon
title: Thomas Harmon
email: tom@harmon.tech
description: A website documenting my projects, experience, and passions.
keywords: "Thomas Harmon, java, developer, web, C++, C, full stack, awesome"
baseurl: "" # the subpath of your site, e.g. /blog
url: harmon.tech

# Info
skills: "Full-Stack Developer - Amazing Person"

# Social media
social:
  - title: linkedin
    url: https://www.linkedin.com/in/tharmony
  - title: github
    url: http://github.com/thomasharmon808
  - title: pdf
    url: http://google.com


permalink: /:title.html

# Webmaster settings
google_verify:
bing_verify:

# Copyright
credits: Copyright Thomas Harmon 2017 

# Build settings
markdown: kramdown
permalink: pretty

# Exclude the following from Jekyll processing when building _site
exclude: [ Gemfile, Gemfile.lock, yarn.lock, node_modules, package.json ]