# Site settings
title: Thomas Harmon
email: tom@harmon.tech
url: https://thomasharmon808.github.io
description: "A website documenting my projects, experience, and passions."
keywords: "Thomas Harmon, java, developer, web, C++, C, full stack, awesome"
skills: "Full-Stack Developer - Amazing Person"
meta_author: Harmon Thomas

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  credits: Credits

# Social networks usernames 
social:
  - title: linkedin
    url: https://www.linkedin.com/in/tharmony
  - title: github
    url: http://github.com/jekyll
  - title: pdf
    url: 


# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>'

# Build settings
markdown: kramdown
permalink: pretty
