# Site settings
author: Thomas Harmon
title: Thomas Harmon
email: tom@harmon.tech
description: A website documenting my projects, experience, and passions.
keywords: "Thomas Harmon, java, developer, web, C++, C, full stack, awesome"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Info
skills: "Full-Stack Developer - Amazing Person"

# Social media
social:
  - title: linkedin
    url: https://www.linkedin.com/in/tharmony
  - title: github
    url: http://github.com/jekyll
  - title: pdf
    url:


# Webmaster settings
google_verify:
bing_verify:

# Copyright
credits: Copyright Thomas Harmon 2017 

# Build settings
markdown: kramdown
permalink: pretty

# Jekyll 3.3 default behavior automatically excludes node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
